export const ROLES = {
  ADMIN: 'admin',
  TABELIAO: 'tabeliao',
  SUBSTITUTO: 'substituto',
  ESCREVENTE: 'escrevente',
  RECEPCAO: 'recepcao',
  FINANCEIRO: 'financeiro',
  CONSULTA: 'consulta',
} as const;

export type RoleName = (typeof ROLES)[keyof typeof ROLES];

export const DEFAULT_ROLE_PERMISSIONS: Record<RoleName, string[]> = {
  [ROLES.ADMIN]: [
    'dashboard:view',
    'people:create', 'people:read', 'people:update', 'people:delete',
    'properties:create', 'properties:read', 'properties:update', 'properties:delete',
    'protocols:create', 'protocols:read', 'protocols:update', 'protocols:delete', 'protocols:cancel', 'protocols:conclude',
    'documents:upload', 'documents:read', 'documents:delete',
    'siscoaf:view', 'siscoaf:analyze', 'siscoaf:configure', 'siscoaf:communicate',
    'users:create', 'users:read', 'users:update', 'users:delete',
    'roles:manage',
    'audit:view', 'audit:export',
    'reports:view', 'reports:export',
    'finance:view', 'finance:manage',
    'settings:manage',
  ],
  [ROLES.TABELIAO]: [
    'dashboard:view',
    'people:create', 'people:read', 'people:update',
    'properties:create', 'properties:read', 'properties:update',
    'protocols:create', 'protocols:read', 'protocols:update', 'protocols:cancel', 'protocols:conclude',
    'documents:upload', 'documents:read',
    'siscoaf:view', 'siscoaf:analyze', 'siscoaf:communicate',
    'users:read',
    'audit:view',
    'reports:view', 'reports:export',
    'finance:view',
  ],
  [ROLES.SUBSTITUTO]: [
    'dashboard:view',
    'people:create', 'people:read', 'people:update',
    'properties:create', 'properties:read', 'properties:update',
    'protocols:create', 'protocols:read', 'protocols:update', 'protocols:conclude',
    'documents:upload', 'documents:read',
    'siscoaf:view', 'siscoaf:analyze',
    'reports:view',
    'finance:view',
  ],
  [ROLES.ESCREVENTE]: [
    'dashboard:view',
    'people:create', 'people:read', 'people:update',
    'properties:create', 'properties:read', 'properties:update',
    'protocols:create', 'protocols:read', 'protocols:update',
    'documents:upload', 'documents:read',
    'siscoaf:view', 'siscoaf:analyze',
  ],
  [ROLES.RECEPCAO]: [
    'dashboard:view',
    'people:create', 'people:read',
    'protocols:create', 'protocols:read',
    'documents:upload',
  ],
  [ROLES.FINANCEIRO]: [
    'dashboard:view',
    'people:read',
    'protocols:read',
    'finance:view', 'finance:manage',
    'reports:view', 'reports:export',
  ],
  [ROLES.CONSULTA]: [
    'dashboard:view',
    'people:read',
    'properties:read',
    'protocols:read',
    'documents:read',
    'reports:view',
  ],
};
