export const SERVICE_CHECKLIST_CONFIG: Record<string, string[]> = {
  COMPRA_VENDA: [
    'RG', 'CPF', 'CERTIDAO_CASAMENTO', 'MATRICULA', 'ITBI', 'CCIR', 'ITR', 'CAR', 'COMPROVANTE_ENDERECO',
  ],
  DOACAO: [
    'RG', 'CPF', 'CERTIDAO_CASAMENTO', 'MATRICULA', 'ITBI', 'ITR', 'COMPROVANTE_ENDERECO',
  ],
  PERMUTA: [
    'RG', 'CPF', 'CERTIDAO_CASAMENTO', 'MATRICULA', 'ITBI', 'CCIR', 'ITR', 'COMPROVANTE_ENDERECO',
  ],
  DIVORCIO: [
    'RG', 'CPF', 'CERTIDAO_CASAMENTO', 'COMPROVANTE_ENDERECO',
  ],
  INVENTARIO: [
    'RG', 'CPF', 'CERTIDAO_CASAMENTO', 'MATRICULA', 'ITR', 'COMPROVANTE_ENDERECO',
  ],
  USUCAPIAO: [
    'RG', 'CPF', 'CERTIDAO_CASAMENTO', 'MATRICULA', 'CCIR', 'ITR', 'COMPROVANTE_ENDERECO',
  ],
  ATA_NOTARIAL: [
    'RG', 'CPF', 'COMPROVANTE_ENDERECO',
  ],
  PROCURACAO: [
    'RG', 'CPF',
  ],
  REVOGACAO: [
    'RG', 'CPF', 'PROCURACAO',
  ],
  TESTAMENTO: [
    'RG', 'CPF', 'CERTIDAO_CASAMENTO', 'COMPROVANTE_ENDERECO',
  ],
  RECONHECIMENTO_FIRMA: [
    'RG', 'CPF',
  ],
  AUTENTICACAO: [],
  APOSTILAMENTO: [
    'RG', 'CPF',
  ],
  CERTIDAO: [
    'RG', 'CPF',
  ],
};
