export const SERVICE_FLOWS: Record<string, { step: string; role: string; description: string }[]> = {
  COMPRA_VENDA: [
    { step: 'RECEPCAO', role: 'recepcao', description: 'Recepção do cliente e documentos' },
    { step: 'ANALISE_DOCUMENTOS', role: 'escrevente', description: 'Análise da documentação' },
    { step: 'VALIDACAO_SISCOAF', role: 'escrevente', description: 'Validação SISCOAF' },
    { step: 'PREPARACAO_ESCRITURA', role: 'escrevente', description: 'Preparação da minuta' },
    { step: 'REVISAO_TABELIAO', role: 'tabeliao', description: 'Revisão do tabelião' },
    { step: 'ASSINATURA', role: 'tabeliao', description: 'Assinatura do ato' },
    { step: 'CONCLUSAO', role: 'tabeliao', description: 'Conclusão e entrega' },
  ],
  DOACAO: [
    { step: 'RECEPCAO', role: 'recepcao', description: 'Recepção do cliente e documentos' },
    { step: 'ANALISE_DOCUMENTOS', role: 'escrevente', description: 'Análise da documentação' },
    { step: 'VALIDACAO_SISCOAF', role: 'escrevente', description: 'Validação SISCOAF' },
    { step: 'PREPARACAO_ESCRITURA', role: 'escrevente', description: 'Preparação da minuta' },
    { step: 'REVISAO_TABELIAO', role: 'tabeliao', description: 'Revisão do tabelião' },
    { step: 'ASSINATURA', role: 'tabeliao', description: 'Assinatura do ato' },
    { step: 'CONCLUSAO', role: 'tabeliao', description: 'Conclusão e entrega' },
  ],
  DIVORCIO: [
    { step: 'RECEPCAO', role: 'recepcao', description: 'Recepção do cliente e documentos' },
    { step: 'ANALISE_DOCUMENTOS', role: 'escrevente', description: 'Análise da documentação' },
    { step: 'PREPARACAO_ESCRITURA', role: 'escrevente', description: 'Preparação da escritura' },
    { step: 'REVISAO_TABELIAO', role: 'tabeliao', description: 'Revisão do tabelião' },
    { step: 'ASSINATURA', role: 'tabeliao', description: 'Assinatura do ato' },
    { step: 'CONCLUSAO', role: 'tabeliao', description: 'Conclusão e entrega' },
  ],
  INVENTARIO: [
    { step: 'RECEPCAO', role: 'recepcao', description: 'Recepção do cliente e documentos' },
    { step: 'ANALISE_DOCUMENTOS', role: 'escrevente', description: 'Análise da documentação' },
    { step: 'AVALIACAO_BENS', role: 'escrevente', description: 'Avaliação dos bens' },
    { step: 'PREPARACAO_ESCRITURA', role: 'escrevente', description: 'Preparação da escritura' },
    { step: 'REVISAO_TABELIAO', role: 'tabeliao', description: 'Revisão do tabelião' },
    { step: 'ASSINATURA', role: 'tabeliao', description: 'Assinatura do ato' },
    { step: 'CONCLUSAO', role: 'tabeliao', description: 'Conclusão e entrega' },
  ],
  USUCAPIAO: [
    { step: 'RECEPCAO', role: 'recepcao', description: 'Recepção do cliente e documentos' },
    { step: 'ANALISE_DOCUMENTOS', role: 'escrevente', description: 'Análise da documentação' },
    { step: 'VALIDACAO_CAR', role: 'escrevente', description: 'Validação CAR' },
    { step: 'PREPARACAO_ATA', role: 'escrevente', description: 'Preparação da ata notarial' },
    { step: 'REVISAO_TABELIAO', role: 'tabeliao', description: 'Revisão do tabelião' },
    { step: 'ASSINATURA', role: 'tabeliao', description: 'Assinatura do ato' },
    { step: 'CONCLUSAO', role: 'tabeliao', description: 'Conclusão e entrega' },
  ],
  ATA_NOTARIAL: [
    { step: 'RECEPCAO', role: 'recepcao', description: 'Recepção do cliente' },
    { step: 'PREPARACAO_ATA', role: 'escrevente', description: 'Preparação da ata' },
    { step: 'REVISAO_TABELIAO', role: 'tabeliao', description: 'Revisão do tabelião' },
    { step: 'ASSINATURA', role: 'tabeliao', description: 'Assinatura do ato' },
    { step: 'CONCLUSAO', role: 'tabeliao', description: 'Conclusão e entrega' },
  ],
  PROCURACAO: [
    { step: 'RECEPCAO', role: 'recepcao', description: 'Recepção do cliente' },
    { step: 'PREPARACAO_PROCURACAO', role: 'escrevente', description: 'Preparação da procuração' },
    { step: 'ASSINATURA', role: 'tabeliao', description: 'Assinatura do ato' },
    { step: 'CONCLUSAO', role: 'tabeliao', description: 'Conclusão e entrega' },
  ],
  TESTAMENTO: [
    { step: 'RECEPCAO', role: 'recepcao', description: 'Recepção do cliente' },
    { step: 'ENTREVISTA', role: 'tabeliao', description: 'Entrevista com o tabelião' },
    { step: 'PREPARACAO_TESTAMENTO', role: 'escrevente', description: 'Preparação do testamento' },
    { step: 'LEITURA_APROVACAO', role: 'tabeliao', description: 'Leitura e aprovação' },
    { step: 'ASSINATURA', role: 'tabeliao', description: 'Assinatura do ato' },
    { step: 'REGISTRO', role: 'escrevente', description: 'Registro no livro' },
    { step: 'CONCLUSAO', role: 'tabeliao', description: 'Conclusão' },
  ],
  RECONHECIMENTO_FIRMA: [
    { step: 'RECEPCAO', role: 'recepcao', description: 'Recepção do cliente' },
    { step: 'VERIFICACAO_ASSINATURA', role: 'escrevente', description: 'Verificação da assinatura' },
    { step: 'CONCLUSAO', role: 'escrevente', description: 'Conclusão e entrega' },
  ],
  AUTENTICACAO: [
    { step: 'RECEPCAO', role: 'recepcao', description: 'Recepção do cliente' },
    { step: 'CONFERENCIA', role: 'escrevente', description: 'Conferência dos documentos' },
    { step: 'CONCLUSAO', role: 'escrevente', description: 'Conclusão e entrega' },
  ],
  APOSTILAMENTO: [
    { step: 'RECEPCAO', role: 'recepcao', description: 'Recepção do cliente' },
    { step: 'VERIFICACAO', role: 'escrevente', description: 'Verificação do documento' },
    { step: 'APOSTILAMENTO', role: 'tabeliao', description: 'Aposição do apostilamento' },
    { step: 'CONCLUSAO', role: 'tabeliao', description: 'Conclusão e entrega' },
  ],
  CERTIDAO: [
    { step: 'RECEPCAO', role: 'recepcao', description: 'Recepção do cliente' },
    { step: 'BUSCA', role: 'escrevente', description: 'Busca no sistema' },
    { step: 'EMISSAO', role: 'escrevente', description: 'Emissão da certidão' },
    { step: 'CONCLUSAO', role: 'escrevente', description: 'Conclusão e entrega' },
  ],
};
